name: pomodoro
description: "Be more productive."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  timer_count_down: ^2.2.0
  group_button: ^5.3.4
  custom_radio_grouped_button: any
  circular_countdown_timer: ^0.2.3
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  google_fonts: ^6.2.1
  golden_toolkit: ^0.15.0
  cool_dropdown: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  fonts:
    - family: Kumbh Sans
      fonts:
        - asset: assets\fonts\KumbhSans-Regular.ttf
        - asset: assets\fonts\KumbhSans-Bold.ttf
    - family: Roboto Slab
      fonts:
        - asset: assets\fonts\RobotoSlab-Regular.ttf
        - asset: assets\fonts\RobotoSlab-Bold.ttf
    - family: Space Mono
      fonts:
        - asset: assets\fonts\SpaceMono-Regular.ttf
        - asset: assets\fonts\SpaceMono-Bold.ttf
  uses-material-design: true
